//테마를 적용합니다.
let themes={
    partynote:{//파스텔톤 베이스
        color_pack:[
            '#FF8A80',
            '#FF80AB',
            '#EA80FC',
            '#B388FF',
            '#8C9EFF',
            '#82B1FF',
            '#80D8FF',
            '#84FFFF',
            '#A7FFEB',
            '#B9F6CA',
            '#CCFF90',
            '#F4FF81',
            '#FFFF8D',
            '#FFE57F',
            '#FFD180',
            '#FF9E80'
            ],
        bg_color_pack:[
            '#FFCCBC',
            '#FFE0B2',
            '#FFECB3',
            '#FFF9C4',
            '#F0F4C3',
            '#DCEDC8',
            '#C8E6C9',
            '#B2DFDB',
            '#B2EBF2',
            '#B3E5FC',
            '#BBDEFB',
            '#C5CAE9',
            '#D1C4E9',
            '#E1BEE7',
            '#F8BBD0',
            '#FFCDD2'
        ]
    },
    blue_mono:{
        color_pack:[
            '#F0F1F5',
            '#AFB8D9',
            '#144988',
            '#57607C',
            '#F0F0F0',
            '#E0E0E0',
            '#D6D6D6',
            '#17284F',
        ],
        bg_color_pack:[
            '#F0F1F5',
            '#F0F0F0',
            '#E0E0E0',
            '#D6D6D6'
        ]
    }
}